name: mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: 3.35.7

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.9.0
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# dart run change_app_package_name:main com.muslim365.mobile

flutter:

  uses-material-design: true
  generate: true # Add this line


  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/svgs/
